name: stuff-nebula-terraform-modules

trigger:
  batch: true
  branches:
    include:
    - 'feature/s3-migration'
    # - "main"
  paths:
    exclude:
    - 'README.md'

# variables:
# - template: ./ci-config.yaml

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Build
    displayName: Build
    steps:
    - checkout: self
    # persistCredentials: true
      displayName: 'Checkout'

    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV3@3
      inputs:
        provider: 'aws'
        command: 'init'
        backendServiceAWS: 'SHARED-SERVICES-nebula-base-TerraformServiceAccount'
        backendAWSBucketName: 'stuff-terraform-nebula'
        backendAWSKey: 'shared/stuff-nebula-terraform-modules-state.tfstate'

    - task: TerraformTaskV3@3
      inputs:
        provider: 'aws'
        command: 'plan'
        commandOptions: '-out=plan'
        environmentServiceNameAWS: 'SHARED-SERVICES-nebula-base-TerraformServiceAccount'
    
    - task: TerraformTaskV3@3
      inputs:
        provider: 'aws'
        command: 'apply'
        commandOptions: '-input=false plan'
        environmentServiceNameAWS: 'SHARED-SERVICES-nebula-base-TerraformServiceAccount'
    
    - bash: |
        bucket_id=`terraform output -raw bucket_id`
        echo "##vso[task.setvariable variable=BUCKET_NAME]$bucket_id"
      workingDirectory: $(Build.SourcesDirectory)
      displayName: Retrieve Bucket Name

    - task: S3Upload@1
      inputs:
        awsCredentials: 'nebula-base-terraform-modules-sa'
        regionName: 'ap-southeast-2'
        bucketName: '$(BUCKET_NAME)'
        sourceFolder: './zips/'
        globExpressions: '**'

