name: stuff-nebula-terraform-modules

trigger:
  batch: true
  branches:
    include:
    - 'feature/s3-migration'
    # - "main"
  paths:
    exclude:
    - 'README.md'

# variables:
# - template: ./ci-config.yaml

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Build
    displayName: Build
    steps:
    - checkout: self
    # persistCredentials: true
      displayName: 'Checkout'