name: stuff-nebula-terraform-modules

trigger:
  batch: true
  branches:
    include:
    - 'feature/s3-migration'
    # - "main"
  paths:
    exclude:
    - 'README.md'

# variables:
# - template: ./ci-config.yaml

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Build
    displayName: Build
    steps:
    - checkout: self
    # persistCredentials: true
      displayName: 'Checkout'

    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV3@3
      displayName: Init Terraform
      inputs:
        provider: 'aws'
        command: 'init'
        backendServiceAWS: 'SHARED-SERVICES-nebula-base-TerraformServiceAccount'
        backendAWSBucketName: 'stuff-terraform-nebula'
        backendAWSKey: 'shared/stuff-nebula-terraform-modules-state.tfstate'

    - task: TerraformTaskV3@3
      displayName: Plan Terraform
      inputs:
        provider: 'aws'
        command: 'plan'
        commandOptions: '-out=plan'
        environmentServiceNameAWS: 'SHARED-SERVICES-nebula-base-TerraformServiceAccount'
    
    - task: TerraformTaskV3@3
      displayName: Apply Terraform
      inputs:
        provider: 'aws'
        command: 'apply'
        commandOptions: '-input=false plan'
        environmentServiceNameAWS: 'SHARED-SERVICES-nebula-base-TerraformServiceAccount'
    - task: PythonScript@0
      displayName: Check Version Status and Prepare Modules - Python Script
      inputs:
        scriptSource: 'filePath'
        scriptPath: './prepare_modules.py'
        failOnStderr: true
    
    - task: AWSShellScript@1
      displayName: Upload New Modules
      inputs:
        awsCredentials: 'nebula-base-terraform-modules-sa'
        regionName: 'ap-southeast-2'
        scriptType: 'filePath'
        filePath: './upload_to_s3.sh'


    # # - task: S3Upload@1
    # #   inputs:
    # #     awsCredentials: 'nebula-base-terraform-modules-sa'
    # #     regionName: 'ap-southeast-2'
    # #     bucketName: '$(BUCKET_NAME)'
    # #     sourceFolder: './zips/'
    # #     globExpressions: '**'

    

